from . import hr_employee
from . import hr_contract
from . import hr_salary_rule
from . import hr_salary_rule_category
from . import hr_payslip_run
from . import hr_payslip
from . import hr_payroll_structure_type
from . import hr_payroll_structure
from . import hr_payslip_worked_days
from . import hr_payslip_input_type
from . import hr_planilla_tabular
from . import hr_salary_attachment